name: Add a tag

on:
  push:

jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "staging"

      - name: Add tag
        run: |
          chmod +x ./scripts/calver.sh
          ./scripts/calver.sh
        shell: bash
