name: Add a tag

on:
  push:

jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "staging"

      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          comment: test message
